import UIKit

public enum URLs {
	public static let baseURL = "https://asia-northeast3-sobok-76d0a.cloudfunctions.net/api"
	public static let signInURL = "/auth/login/email"
	public static let signUpURL = "/auth/signup"
	public static let checkUsernameURL = "/user/name"
	public static let getCalendarURL = "/schedule/my"
	public static let getPillListURL = "/schedule/my/detail"
	public static let editPillListURL = "/pill/{pillId}"
	public static let stopPillListURL = "/pill/stop/{pillId}"
	public static let deletePillURL = "/pill/{pillId}"
	public static let checkPillURL = "/schedule/check/{scheduleId}"
	public static let uncheckPillURL = "/schedule/uncheck/{scheduleId}"
	public static let checkStickerURL = "/sticker/{scheduleId}"
	public static let getGroupInfoURL = "/group"
	public static let getFriendCalendarURL = "/schedule/{memberId}"
	public static let getFriendPillListURL = "/schedule/{memberId}/detail"
	public static let editFriendUsernameURL = "/group/{groupId}/name"
	public static let getStickerURL = "/sticker"
	public static let postStickerURL = "/sticker/{schedlueId}"
	public static let editStickerURL = "/sticker/my/{likeScheduleId}"
	public static let getFriendsURL = "/user"
	public static let postCalendarURL = "/group"
	public static let acceptCalendarURL = "/group/{sendGroupId}"
	public static let getNoticeListURL = "/notice/list"
	public static let getPillNoticeURL = "/notice"
	public static let acceptPillNoticeURL = "/notice"
	public static let addMyPillURL = "/pill"
	public static let addFriendPillURL = "/pill/{receiverId}"
	public static let getFriendPillCountURL = "/pill/{userId}"
	public static let getMyPillCountURL = "/pill/count"
}